### PR TITLE
Added additional standalone options

### PR DESCRIPTION
**Pull request by peterjohnsonme**

### CODE REVIEW

**Comment by peterjohnsonme** [comment]
Not entirely sure if you intended this to be a V3 version of the plugin or not, that's the route I went down. Tested this in my own Azure devops environment for the Windows 32-bit, Windows 64-bit, and Mac Standalone versions, and modifying the .exe name.

**Comment by peterjohnsonme** [comment]
Sure, I guess it makes sense to have the agent-based option, what do you think of "Standalone (agent-based)".  Then the configuration is completely backward-compatible.

Regarding the version, do I set it as something like 2.1.0?

**Comment by FejZa** [comment]
I think Standalone (agent-based) makes sense. That way it's clear that the agent's OS dictates the output.  I am using semantic versioning here and since you added new functionality in a backwards compaitble manner, 2.1.0 is the right version yes. Thanks a lot!

**Comment by peterjohnsonme** [comment]
Not sure how the versioning should work with the marketplace versions.  Should I just modify the task.json version and update the UnityBuildV2 folder, or create a UnityBuildV2_1 folder?

**Comment by FejZa** [comment]
Thanks again, your changes are now published to the marketplace as well.

**Pull request merged**
