### PR TITLE
Update AzureDevOps.cs to pass Code Analysis Quality rules

### PR DESCRIPTION
**Pull request by paulio**
Microsoft Code Quality Analyzer detects 3 rule failures in the existing code. These can be fixed by; a) suppressing the rules (pragma disable/restore or b) fixing the problem (adding a namespace) c) working around the problem (when ex is exception)

### CODE REVIEW

**Comment by FejZa** [comment]
Could you please list the rule failures the analyzer is reporting here?

**Comment by paulio** [comment]
- [CA1052 Static holder types should be Static or NotInheritable](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1052) 
- [CA1031 Do not catch general exception types](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1031)
-  [CA1050 Declare types in namespaces](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1050)

**Comment by paulio** [comment]
Hi, would it be possible to get an update on if there are any plans to offer a feature around this, or if this PR or similar will be merged in the near future?

**Review by FejZa — APPROVED** [review]

**Comment by FejZa** [comment]
Looks good, thank you @paulio. Will add it to the next release.

**Pull request merged**
