### PR TITLE
v2.9.7

### PR DESCRIPTION
**Pull request by FejZa**
### Added

- [Introduce new configuration option to build using build profiles](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/pull/276)
- [Add option to produce .aab file instead of .apk for Android builds](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/pull/270)
- [Add Android signing option to build task](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/pull/269)
- [Add UnityGetProjectVersionTask tests](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/pull/278)
- [Add new task UnityCreateProjectV1](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/pull/283)

### Changed

- [Revert UnityCMD deprecation and align input options with other tasks](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/pull/268)
- [Update UnityGetProjectVersionV1 shared library dependency](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/pull/281)
- [Adjust log output variable to point to log file](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/pull/284)

### CODE REVIEW

**Comment by FejZa** [comment]
Hello @bdovaz,

everything is ready for the release. Do let me know, if you have time to take a look at the changes made. I have also fixed the tests for good this time :)

**Comment by bdovaz** [comment]
@FejZa in this PR I made comments to you that you did not answer: https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/pull/269

**Comment by FejZa** [comment]
I do not see any comments/questions @bdovaz ?

**Comment by FejZa** [comment]
I can literally not see any of these comments, hence I did not answer them. I did also never get a mail that a review has been made. Need to double check what is going on.

I think prefixing the new android variables is a great idea! For the build targets it is fine to leave them as they are. There are not really frequent changes in those options and with the new build profiles this is sorts of going to vanish in the upcoming years.

**Comment by bdovaz** [comment]
> I think I know what happened @bdovaz. You started a review but never completed it. That's why it sayss "Pending" in your image. Until you complete a review I cannot see any of your comments.

Ok, I just completed it, sorry, I work with Azure DevOps, I am new to PR reviews on GitHub.

**Comment by FejZa** [comment]
All right. I think we are ready to ship this release.

**Pull request merged**
