### PR TITLE
Added support for Unity Personal manual licenses. [Needs Testing]

### PR DESCRIPTION
**Pull request by TheDudeFromCI**
Added support for handling Unity Personal manual activation files via the same workflow as:
https://github.com/webbertakken/unity-actions

This PR needs testing but should work in theory.

This works by allowing the manual activation file to be specified within the serial option while setting  `activationMode` to `Unity Personal`. In addition, an extra build task was written for the sole purpose of generating the manual activation file.

Intended Workflow:
* Setup the pipeline with just two tasks. First, requesting the manual activation file. Don't even need the Unity project, it just needs to run on the Azure machine.  After this, a second task can be used to upload the activation file as an artifact to Azure.
* Run the pipeline and download the artifact.
* Upload the file to https://license.unity3d.com/manual and activate it.
* Take the newly activated license and put it back onto Azure pipelines as a secret variable.
* Delete the previous tasks. We don't need them anymore. Instead, write a task to write the contents of the secret to a file with the name `Unity_vVERSION.alf` where VERSION is the Unity version.
* Add an activation task after this setting the serial to `Unity_vVERSION.alf`, same as above. Set the `activationMode` to `Unity Personal`
* Write the rest of your Unity Build and Unity Test tasks as you normally would.

After the first part, you don't need to activate the license anymore. It remains active for all future runs.

Concerns:
The only concern I have is that this relies on the premise that Azure pipeline builds are consistent. I.e, run on a machine of the same specs each time. The Unity manual license uses the machine specs for activation. I'm not sure how Azure handles this.

### CODE REVIEW

**Comment by FejZa** [comment]
Hi @TheDudeFromCI, 

this sounds awesome! I'll be sure to test and get it in as soon as I get to! Thanks a lot.

**Comment by devedse** [comment]
@TheDudeFromCI I really like this, @FejZa , can this be merged in :)?

**Comment by FejZa** [comment]
Hi @TheDudeFromCI, could you please retarget this PR to the master branch?

**Comment by devedse** [comment]
@TheDudeFromCI , to get this to work on Azure DevOps CI machines I created my own tool: https://github.com/devedse/DeveUnityLicenseActivator

It basically does the activation of the .alf file automatically using a scripted browser.

**Pull request closed without merging**
