### PR TITLE
Move logs output to the agent's temporary directory

### LINKED ISSUE #246: Generate logs in another path
@FejZa currently, it is generated in a /Logs folder in the repository root.

It would make sense to generate it in a another path so that it is not so intrusive (i.e. does not generate a file in the working copy of the repository).

There are 2 decisions to make:
* Whether to make the path configurable and have the default value remain the same.
* Change it directly to another more logical path like $(Agent.TempDirectory).

The second one is simpler because as the tasks expose output variables with the log paths, if you only depend on that which is logical, there is no breaking change.

The only breaking change can be created if you don't use the ouput variable and "trust" that there is always a /Logs path in the repository root.

### PR DESCRIPTION
**Pull request by bdovaz**
Fixes #246

### CODE REVIEW

**Comment by bdovaz** [comment]
@FejZa please, merge this PR and release a new version.

Thanks!

**Comment by FejZa** [comment]
hey @bdovaz I'll merge and test asap.

**Comment by FejZa** [comment]
Getting this and your other PR published by end of the weekend  @bdovaz. Sorry, can't make it eralier. I appreciate your contribution a lot!

**Comment by bdovaz** [comment]
Ok, thank you!

**Review by FejZa — APPROVED** [review]

**Pull request merged**
