### PR TITLE
Add UnityGetProjectVersionTask tests

### PR DESCRIPTION
**Pull request by bdovaz**

### CODE REVIEW

**Comment by bdovaz** [comment]
@FejZa as I told you, being in Azure Pipelines I can't see the errors.... So I can't see what happened

**Comment by FejZa** [comment]
I'll check today @bdovaz. As I said, I am fine with movikg this to GitHub Action's but after this week's release. I'll check why the build fails later today.

**Review by FejZa — APPROVED** [review]

**Comment by FejZa** [comment]
This was failing because the pipeline omits dev dependencies when building the release bundle. We'll modify this to only omit when buliding a release build once we move to GitHub actions

**Comment by FejZa** [comment]
The pipeline works fine now but fails because one of the tests fails:

```
 Unity Get Project Version
Downloading file: https://nodejs.org/dist/v20.13.1/node-v20.13.1-linux-x64.tar.gz
    1) Error determining the project version from file
    ✔ Success (alpha) determining the project version from file (319ms)
    ✔ Success (beta) determining the project version from file (305ms)
    ✔ Success (stable) determining the project version from file (307ms)


  3 passing (4s)
  1 failing

  1) Unity Get Project Version
       Error determining the project version from file:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/vsts/work/1/s/Tasks/UnityGetProjectVersion/UnityGetProjectVersionV1/test/_suite.js)

```

**Comment by FejZa** [comment]
Locally all the tests are failing for me

`Error: EPERM: operation not permitted, unlink 'C:\Users\Dino\azure-pipelines-task-lib\_download\node20\node.exe.download'
`ShellJSInternalError: EPERM: operation not permitted, lstat 'C:\Users\Dino\azure-pipelines-task-lib\_download\node20\node.exe.download'``

**Comment by FejZa** [comment]
Is there some special setup required for the tests to run correctly?

**Comment by FejZa** [comment]
```
 Unity Get Project Version
Downloading file: https://nodejs.org/dist/v20.13.1/win-x64/node.exe
    1) Error determining the project version from file
rm: could not remove directory (code ENOTEMPTY): C:/Users/Dino/azure-pipelines-task-lib/_download/node20
Downloading file: https://nodejs.org/dist/v20.13.1/win-x64/node.exe
    2) Success (alpha) determining the project version from file
    3) Success (beta) determining the project version from file
    4) Success (stable) determining the project version from file


  0 passing (3s)
  4 failing
```

Why does it appear to be trying to download a Noxe executable when running the tests?

**Comment by FejZa** [comment]
Ok moved to GitHub actions and for some reason the test seem to pass now. Must have been an agent config issue. But still need to figure out why it fails locally for me.

**Comment by bdovaz** [comment]
@FejZa I honestly don't understand the problem either. It seems to have something to do with this?

https://stackoverflow.com/questions/44149096/for-async-tests-and-hooks-ensure-done-is-called-if-returning-a-promise-en

**Pull request merged**
